export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_ERRORS = 'GET_ERRORS';

export const LOGIN_MODAL_TOGGLE = 'LOGIN_MODAL_TOGGLE';
export const REGISTER_MODAL_TOGGLE = 'REGISTER_MODAL_TOGGLE';

export const LOAD_PRIVATE_RANKINGS_START = 'LOAD_PRIVATE_RANKINGS_START';
export const LOAD_PRIVATE_RANKINGS_SUCCESS = 'LOAD_PRIVATE_RANKINGS_SUCCESS';
export const LOAD_PRIVATE_RANKINGS_FAIL = 'LOAD_PRIVATE_RANKINGS_FAIL';

export const LOAD_PUBLIC_RANKINGS_START = 'LOAD_PUBLIC_RANKINGS_START';
export const LOAD_PUBLIC_RANKINGS_SUCCESS = 'LOAD_PUBLIC_RANKINGS_SUCCESS';
export const LOAD_PUBLIC_RANKINGS_FAIL = 'LOAD_PUBLIC_RANKINGS_FAIL';

export const LOAD_RANKING_START = 'LOAD_RANKING_START';
export const LOAD_RANKING_SUCCESS = 'LOAD_RANKING_SUCCESS';
export const LOAD_RANKING_FAIL = 'LOAD_RANKING_FAIL';

export const RANKING_LIKE = 'RANKING_LIKE';
export const RANKING_DISLIKE = 'RANKING_DISLIKE';
export const RANKING_SHARE = 'RANKING_SHARE';
export const RANKING_COMMENT = 'RANKING_COMMENT';
