export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_ERRORS = 'GET_ERRORS';

export const LOGIN_MODAL_TOGGLE = 'LOGIN_MODAL_TOGGLE';
export const REGISTER_MODAL_TOGGLE = 'REGISTER_MODAL_TOGGLE';

export const CLOSE_MODAL = 'CLOSE_MODAL';

export const LOAD_PRIVATE_RANKINGS_START = 'LOAD_PRIVATE_RANKINGS_START';
export const LOAD_PRIVATE_RANKINGS_SUCCESS = 'LOAD_PRIVATE_RANKINGS_SUCCESS';
export const LOAD_PRIVATE_RANKINGS_FAIL = 'LOAD_PRIVATE_RANKINGS_FAIL';
export const LOAD_MORE_PRIVATE_RANKINGS_START = 'LOAD_MORE_PRIVATE_RANKINGS_START';
export const LOAD_MORE_PRIVATE_RANKINGS_SUCCESS = 'LOAD_MORE_PRIVATE_RANKINGS_SUCCESS';
export const LOAD_MORE_PRIVATE_RANKINGS_FAIL = 'LOAD_MORE_PRIVATE_RANKINGS_FAIL';

export const LOAD_PUBLIC_RANKINGS_START = 'LOAD_PUBLIC_RANKINGS_START';
export const LOAD_PUBLIC_RANKINGS_SUCCESS = 'LOAD_PUBLIC_RANKINGS_SUCCESS';
export const LOAD_PUBLIC_RANKINGS_FAIL = 'LOAD_PUBLIC_RANKINGS_FAIL';
export const LOAD_MORE_PUBLIC_RANKINGS_START = 'LOAD_MORE_PUBLIC_RANKINGS_START';
export const LOAD_MORE_PUBLIC_RANKINGS_SUCCESS = 'LOAD_MORE_PUBLIC_RANKINGS_SUCCESS';

export const LOAD_FOLLOWING_RANKINGS_START = 'LOAD_FOLLOWING_RANKINGS_START';
export const LOAD_FOLLOWING_RANKINGS_SUCCESS = 'LOAD_FOLLOWING_RANKINGS_SUCCESS';
export const LOAD_FOLLOWING_RANKINGS_FAIL = 'LOAD_FOLLOWING_RANKINGS_FAIL';
export const LOAD_MORE_FOLLOWING_RANKINGS_START = 'LOAD_MORE_FOLLOWING_RANKINGS_START';
export const LOAD_MORE_FOLLOWING_RANKINGS_SUCCESS = 'LOAD_MORE_FOLLOWING_RANKINGS_SUCCESS';
export const LOAD_MORE_FOLLOWING_RANKINGS_FAIL = 'LOAD_MORE_FOLLOWING_RANKINGS_FAIL';

export const LOAD_RANKING_START = 'LOAD_RANKING_START';
export const LOAD_RANKING_SUCCESS = 'LOAD_RANKING_SUCCESS';
export const LOAD_RANKING_FAIL = 'LOAD_RANKING_FAIL';

export const RANKING_LIKE = 'RANKING_LIKE';
export const RANKING_DISLIKE = 'RANKING_DISLIKE';
export const RANKING_SHARE = 'RANKING_SHARE';
export const COMMENT_RANKING_SUCCESS = 'COMMENT_RANKING_SUCCESS';

export const LOAD_COMMENTS_START = 'LOAD_COMMENTS_START';
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const LOAD_MORE_COMMENTS_START = 'LOAD_MORE_COMMENTS_START';
export const LOAD_MORE_COMMENTS_SUCCESS = 'LOAD_MORE_COMMENTS_SUCCESS';
export const TOGGLE_COMMENT_FORM = 'TOGGLE_COMMENT_FORM';
export const SUBMIT_COMMENT_FORM = 'SUBMIT_COMMENT_FORM';

export const CREATE_RANKING_START = 'CREATE_RANKING_START';
export const CREATE_RANKING_SUCCESS = 'CREATE_RANKING_SUCCESS';
export const CREATE_RANKING_FAIL = 'CREATE_RANKING_FAIL';

export const EDIT_RANKING_START = 'EDIT_RANKING_START';
export const EDIT_RANKING_SUCCESS = 'EDIT_RANKING_SUCCESS';
export const EDIT_RANKING_FAIL = 'EDIT_RANKING_FAIL';

export const ADD_POSITION_START = 'ADD_POSITION_START';
export const ADD_POSITION_SUCCESS = 'ADD_POSITION_SUCCESS';
export const ADD_POSITION_FAIL = 'ADD_POSITION_FAIL';

export const SHARE_MODAL_TOGGLE = 'SHARE_MODAL_TOGGLE';

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const FETCH_USER_RANKINGS_START = 'FETCH_USER_RANKINGS_START';
export const FETCH_USER_RANKINGS_SUCCESS = 'FETCH_USER_RANKINGS_SUCCESS';
export const FETCH_USER_RANKINGS_FAIL = 'FETCH_USER_RANKINGS_FAIL';
export const FETCH_MORE_USER_RANKINGS_START = 'FETCH_MORE_USER_RANKINGS_START'
export const FETCH_MORE_USER_RANKINGS_SUCCESS = 'FETCH_MORE_USER_RANKINGS_SUCCESS'

export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';

export const EDIT_PROFILE_START = 'EDIT_PROFILE_START';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';